# Generated by Django 5.0.6 on 2026-05-28 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('canonical_name', models.CharField(max_length=255)),
                ('normalized_name', models.CharField(help_text='Lower-case, accent-stripped, prefix-free version of canonical_name.', max_length=255, unique=True)),
                ('aliases', models.JSONField(blank=True, default=list)),
                ('mention_count', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ('canonical_name',),
                'indexes': [models.Index(fields=['normalized_name'], name='people_pers_normali_bc33d0_idx')],
            },
        ),
    ]
