# Generated by Django 5.0.6 on 2026-05-28 15:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('articles', '0001_initial'),
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Relationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('relationship_type', models.CharField(max_length=100)),
                ('explanation', models.TextField(blank=True, default='')),
                ('evidence_sentence', models.TextField(blank=True, default='')),
                ('confidence', models.FloatField(default=0.0)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relationships', to='articles.article')),
                ('source_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_relationships', to='people.person')),
                ('target_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_relationships', to='people.person')),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['relationship_type'], name='relationshi_relatio_f0f539_idx'), models.Index(fields=['source_person', 'target_person'], name='relationshi_source__dc5a7a_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='relationship',
            constraint=models.UniqueConstraint(fields=('source_person', 'target_person', 'relationship_type', 'article', 'evidence_sentence'), name='uniq_relationship_provenance'),
        ),
        migrations.AddConstraint(
            model_name='relationship',
            constraint=models.CheckConstraint(check=models.Q(('source_person', models.F('target_person')), _negated=True), name='relationship_no_self_loop'),
        ),
    ]
