# Generated by Django 5.0.6 on 2026-05-28 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('url', models.URLField(max_length=1000, unique=True)),
                ('title', models.CharField(max_length=500)),
                ('content', models.TextField(blank=True, default='')),
                ('summary', models.TextField(blank=True, default='')),
                ('author_name', models.CharField(blank=True, default='', max_length=255)),
                ('source', models.CharField(default='techcrunch', help_text='Identifier of the crawler/source that produced this article.', max_length=64)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('crawled_at', models.DateTimeField(auto_now_add=True)),
                ('last_ingested_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ('-published_at', '-created_at'),
                'indexes': [models.Index(fields=['source'], name='articles_ar_source_1c4e07_idx'), models.Index(fields=['published_at'], name='articles_ar_publish_a51805_idx')],
            },
        ),
    ]
